// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import path from "path";
import dotenv from "dotenv";

// Load .env from the frontend directory explicitly and prefer it over shell env
const envPath = path.resolve(__dirname, ".env");
const envFile = dotenv.config({ path: envPath });
const fileUrl = envFile.parsed?.DATABASE_URL;

const defaultUrl = "postgresql://postgres:example@localhost:5437/prompt_wars?schema=public";
const datasourceUrl = fileUrl || process.env.DATABASE_URL || defaultUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Prefer .env value, then shell env, then default 5437
    url: datasourceUrl,
  },
});
