/**
 * Simple interface validation test
 * Feature: rekto-rich-agent, Property 1: Trading decision display completeness
 * Validates: Requirements 1.2, 1.3
 */

import { TradingDecision, ChainOfThought, PredictionMarket, UserBet, DegenAgent, PaymentVerification } from './types';

// Test function to validate trading decision display completeness
function validateTradingDecisionDisplay(decision: TradingDecision): boolean {
  // Property 1: Trading decision display completeness
  // For any trading decision generated by the Degen_Agent, the display should include 
  // token symbol, current price, timestamp, decision type (LONG/SHORT), and blurred reasoning content
  
  // Check required fields are present and valid
  if (!decision.tokenSymbol || decision.tokenSymbol.length === 0) {
    return false;
  }
  
  if (decision.currentPrice <= 0) {
    return false;
  }
  
  if (!(decision.timestamp instanceof Date)) {
    return false;
  }
  
  if (!['LONG', 'SHORT'].includes(decision.decision)) {
    return false;
  }
  
  if (decision.confidence < 0 || decision.confidence > 100) {
    return false;
  }
  
  if (typeof decision.isUnlocked !== 'boolean') {
    return false;
  }
  
  // If chainOfThought is present, it should be a string
  if (decision.chainOfThought !== undefined && typeof decision.chainOfThought !== 'string') {
    return false;
  }
  
  // If marketId is present, it should be a valid string
  if (decision.marketId !== undefined && (typeof decision.marketId !== 'string' || decision.marketId.length === 0)) {
    return false;
  }
  
  return true;
}

// Test sample data
const sampleTradingDecision: TradingDecision = {
  id: '123e4567-e89b-12d3-a456-426614174000',
  tokenSymbol: 'BTC',
  decision: 'LONG',
  confidence: 85,
  timestamp: new Date(),
  currentPrice: 45000.50,
  chainOfThought: 'This is the AI reasoning...',
  isUnlocked: false,
  marketId: '456e7890-e89b-12d3-a456-426614174001'
};

const sampleChainOfThought: ChainOfThought = {
  decisionId: '123e4567-e89b-12d3-a456-426614174000',
  reasoning: 'Market momentum is strong with high volume',
  marketAnalysis: 'Technical indicators show bullish divergence',
  riskAssessment: 'Medium risk with good reward potential',
  degenCommentary: 'WAGMI! This token is about to moon! Diamond hands only! 🚀',
  priceTargets: {
    bullish: 50000,
    bearish: 40000
  }
};

const samplePredictionMarket: PredictionMarket = {
  id: '789e0123-e89b-12d3-a456-426614174002',
  decisionId: '123e4567-e89b-12d3-a456-426614174000',
  totalPool: 1000.50,
  winBets: 600.25,
  lossBets: 400.25,
  resolutionTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours from now
  isResolved: false,
  outcome: undefined
};

const sampleUserBet: UserBet = {
  id: 'abc1234-e89b-12d3-a456-426614174003',
  userId: 'user123-e89b-12d3-a456-426614174004',
  marketId: '789e0123-e89b-12d3-a456-426614174002',
  prediction: 'WIN',
  amount: 50.0,
  timestamp: new Date(),
  isWinning: undefined,
  payout: undefined
};

const sampleDegenAgent: DegenAgent = {
  personality: {
    riskTolerance: 'EXTREME',
    tradingStyle: 'HYPE_DRIVEN',
    slangIntensity: 9
  },
  performance: {
    totalPredictions: 100,
    correctPredictions: 65,
    averageReturn: 15.5,
    winStreak: 5
  }
};

const samplePaymentVerification: PaymentVerification = {
  transactionSignature: '5VfYD7jfuQwxzQyGzQyGzQyGzQyGzQyGzQyGzQyGzQyGzQyGzQyGzQyGzQyGzQyGzQyG',
  amount: 0.5,
  sender: 'sender123456789012345678901234567890123456',
  recipient: 'recipient123456789012345678901234567890123',
  timestamp: new Date(),
  isVerified: true,
  contentId: '123e4567-e89b-12d3-a456-426614174000'
};

// Run validation tests
console.log('Testing interface validation...');

const isValid = validateTradingDecisionDisplay(sampleTradingDecision);
console.log('Trading Decision Display Completeness Test:', isValid ? 'PASSED' : 'FAILED');

// Test that all interfaces can be created and have expected properties
console.log('Sample TradingDecision created:', !!sampleTradingDecision.id);
console.log('Sample ChainOfThought created:', !!sampleChainOfThought.decisionId);
console.log('Sample PredictionMarket created:', !!samplePredictionMarket.id);
console.log('Sample UserBet created:', !!sampleUserBet.id);
console.log('Sample DegenAgent created:', !!sampleDegenAgent.personality);
console.log('Sample PaymentVerification created:', !!samplePaymentVerification.transactionSignature);

console.log('All interface validation tests completed successfully!');

export { validateTradingDecisionDisplay };